[project]
name = "cosmetic-ingredient-analysis-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "dbt-bigquery>=1.9.1",
    "ipykernel>=6.29.5",
]
