SELECT
    scanlog_id,
    user_id,
    barcode,
    created_at,
    created_date, 
    created_week,
    created_month,
    updated_at,
    updated_date,
    birth_date,
    gender,
    gender_jp,
    age_at_current,
    age_at_scanned,
    age_group,
    CONCAT(age_group, ' ', gender_jp) AS gender_age,
    skin_type,
    skin_problems,
    skin_problems_cnt,
    product_id,
    product_name,
    company_name,
    cosmetic_category,
    ingredients,
FROM {{ref('int_scanlogs_joined')}}
